# Generated by Django 6.0.3 on 2026-03-14 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0002_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField(blank=True, null=True)),
                ('time_message', models.DateTimeField(default=django.utils.timezone.now)),
                ('view_message', models.BooleanField()),
                ('file_message', models.FileField(blank=True, null=True, upload_to='')),
                ('image_message', models.ImageField(blank=True, null=True, upload_to='')),
                ('resend_message', models.BooleanField()),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Chats.chat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
