# Generated by Django 6.0.3 on 2026-03-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='juegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_juegos', models.CharField(max_length=50)),
                ('calification_juegos', models.CharField(max_length=50)),
                ('image_juegos', models.CharField(max_length=50)),
                ('genero_juegos', models.CharField(max_length=50)),
            ],
        ),
    ]
