# Generated by Django 6.0.3 on 2026-03-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0006_juegos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='juegos',
        ),
    ]
