# Generated by Django 6.0.3 on 2026-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0007_delete_juegos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='online_user',
            new_name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
