# Generated by Django 6.0.3 on 2026-04-05 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0008_rename_online_user_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
