# Generated by Django 6.0.3 on 2026-04-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0009_chat_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_grupal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
