# Generated by Django 6.0.3 on 2026-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0010_chat_chat_grupal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_user',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
