# Generated by Django 6.0.3 on 2026-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0011_alter_user_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='resend_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='view_message',
            field=models.BooleanField(default=False),
        ),
    ]
